// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZooMVC.Models;

namespace ZooMVC.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20190926112040_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ZooMVC.Models.Habitat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ItineraryId");

                    b.Property<string>("Name");

                    b.Property<string>("Vegetation");

                    b.Property<string>("Weather");

                    b.HasKey("Id");

                    b.HasIndex("ItineraryId");

                    b.ToTable("Habitat");
                });

            modelBuilder.Entity("ZooMVC.Models.HabitatSpecie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HabitatId");

                    b.Property<int>("Index");

                    b.Property<int?>("SpecieId");

                    b.Property<int>("SpieceId");

                    b.HasKey("Id");

                    b.HasIndex("HabitatId");

                    b.HasIndex("SpecieId");

                    b.ToTable("HabitatSpecie");
                });

            modelBuilder.Entity("ZooMVC.Models.Itinerary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<int>("Duration");

                    b.Property<int>("Length");

                    b.Property<int>("Visitors");

                    b.HasKey("Id");

                    b.ToTable("Itinerary");
                });

            modelBuilder.Entity("ZooMVC.Models.Specie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClientName");

                    b.Property<string>("Description");

                    b.Property<string>("FullName");

                    b.Property<string>("Picture");

                    b.HasKey("Id");

                    b.ToTable("Specie");
                });

            modelBuilder.Entity("ZooMVC.Models.Habitat", b =>
                {
                    b.HasOne("ZooMVC.Models.Itinerary", "Itinerary")
                        .WithMany("Habitats")
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ZooMVC.Models.HabitatSpecie", b =>
                {
                    b.HasOne("ZooMVC.Models.Habitat", "Habitat")
                        .WithMany("HabitatsSpecies")
                        .HasForeignKey("HabitatId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ZooMVC.Models.Specie", "Specie")
                        .WithMany("HabitatsSpecies")
                        .HasForeignKey("SpecieId");
                });
#pragma warning restore 612, 618
        }
    }
}
